apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge-inference-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edge-inference-service
            port:
              number: 6767
